// src/main/content/about_me.tsx
// import react, { useState, useEffect } from 'react';
import { Grid, Typography, Box } from "@mui/material";
import { languages } from '../../data/me';

export default function AboutMe() {
    return(
        <Grid container spacing={0}>
            <Grid item className="intro-box">
                <div className="text-intro">
                    <Typography className="hi">HI THERE!</Typography>
                    <Typography className="name">I'M <span className="highlight">NADIA TIWING</span></Typography>
                    <Typography className="job-title"> SOFTWARE DEVELOPER </Typography>
                    <Typography className="summary" >
                        I love developing a software applications that help people's lives easier and has more than 6 years experience in building, designing,  testing, and implementing a cutting-edge engineering solutions. Also, I am able to consult well with clients and enhances configuration for optimal customer satisfaction. I am skilled at team collaboration while working independently in remote environments.
                    </Typography>
                </div>
            </Grid>
            <Grid item container className="skills">
                <Grid item>
                    <Typography className="hi">TECH SKILLS:</Typography>
                </Grid>
                <Grid container flexDirection="row" alignItems="center" justifyContent="start">
                    <Grid item pr={2}>
                        <Typography sx={{ opacity: "0.5"}}>Legends: </Typography>
                    </Grid>
                    <Grid item>
                        <Box className="legends" sx={{ opacity: "0.5"}}>
                            <span className="custom-badge expert"></span><label className="txt">Advanced</label>
                            <span className="custom-badge proficient"></span><label className="txt">Proficient</label>
                            <span className="custom-badge novice"></span><label className="txt">Novice</label>
                        </Box>
                    </Grid>
                </Grid>
                <Grid item>
                    <div className='languages'>
                        {languages.map( lang => (
                            <div className="legends" key={lang.name}>
                                <span className={`custom-badge ${lang.level}`}></span><label className="txt">{lang.name}</label>
                            </div>
                        ))}
                    </div>
                </Grid>
            </Grid>
        </Grid>
    );
}

// src/pages/about-me/index.svelte
<script lang="ts">
	import SectionHeading from '$lib/components/SectionHeading.svelte';
	import Card from '$lib/components/Card.svelte';
	import Badge from '$lib/components/Badge.svelte';
	import me from '../../data/me.json' with { type: 'json' };

	const levels = ['expert', 'proficient', 'novice'] as const;
	const levelLabel: Record<string, string> = {
		expert: 'Advanced',
		proficient: 'Proficient',
		novice: 'Novice'
	};

	const grouped = levels.map((level) => ({
		level,
		items: me.languages.filter((l) => l.level === level)
	}));
</script>

<section class="page">
	<div class="stack">
		<p class="role mono">// software engineer</p>
		<h1>Nadia Tiwing</h1>
		<p>
			Have 7 years experience in developing and architecting software applications that make
			people's lives easier — building, designing, testing, and implementing cutting-edge
			engineering solutions. I consult well with clients and enhance configurations for optimal
			customer satisfaction. I'm skilled at team collaboration while working independently in
			remote environments, and I find satisfaction in solving complex problems and continuously
			learning new technologies.
		</p>
	</div>

	<div class="stack">
		<SectionHeading tag="tech skills" />
		<Card hover={false}>
			<div class="stack">
				{#each grouped as group}
					<div class="skill-group">
						<span class="label">{levelLabel[group.level]}</span>
						<div class="badge-row">
							{#each group.items as skill}
								<Badge label={skill.name} variant={group.level} dot />
							{/each}
						</div>
					</div>
				{/each}
			</div>
		</Card>
	</div>
</section>
